### PR TITLE
Adding descriptions

### PR DESCRIPTION
**Pull request by forki**
This is a super ugly protoytpe for allowing to show what the computer player "thinks" about a position. For now it's only implemented for MCTS and my UI skills are so bad. But I think it will help us to improve the algorithms

image

### CODE REVIEW

**Comment by forki** [comment]
The information that minimax gives is a bit different. MCTS is thinking in Chances (0.54 means I have 54% chance to win). Minimax evaluates the position differently. So the format needs to be somewhat free

**Comment by markpattison** [comment]
I did some work to allow the descriptions to be hierarchical and let you expand/hide them:

reversi

**Comment by forki** [comment]
Awesome. Would love to see same thing for minimax

**Comment by markpattison** [comment]
That's there too but only one level deep at the moment:

reversi

**Comment by forki** [comment]
If you let two engines play against each other than the descriptions is collapsed all the time.

**Pull request merged**
